services:
  db:
    image: mysql:8.0
    container_name: toolrent-db
    environment:
      MYSQL_ROOT_PASSWORD: 5036
      MYSQL_DATABASE: toolrent_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p5036"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: toolrent-keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: 5036
      KEYCLOAK_ADMIN: IsiAdmin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    ports:
      - "8081:8080"
    command: start-dev
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: isidorarojas/toolrent-backend:latest
    container_name: toolrent-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: toolrent_db
      DB_USERNAME: root
      DB_PASSWORD: 5036
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: toolrent-realm
    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: isidorarojas/toolrent-frontend:latest
    container_name: toolrent-frontend
    ports:
      - "8070:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data: