spring:
  application:
    name: toolrent
  datasource:
    url: jdbc:mysql://${DB_HOST:db}:${DB_PORT:3306}/${DB_NAME:toolrent_db}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:5036}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        provider:
          keycloak:
            # NO usar issuer-uri aquí, definir TODO manualmente
            authorization-uri: http://localhost:8081/realms/toolrent-realm/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/toolrent-realm/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/toolrent-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/toolrent-realm/protocol/openid-connect/certs
            user-name-attribute: preferred_username
            # CRÍTICO: Especificar issuer para validación de tokens
            issuer-uri: http://keycloak:8080/realms/toolrent-realm
        registration:
          keycloak:
            provider: keycloak
            client-id: toolrent-backend
            client-secret: ${KEYCLOAK_CLIENT_SECRET:pYvZAJ4Vjj7mFbVOxQW3S6nZNrQztdYT}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/keycloak
            scope:
              - openid
              - profile
              - email
      resourceserver:
        jwt:
          # URL interna para validar tokens
          jwk-set-uri: http://keycloak:8080/realms/toolrent-realm/protocol/openid-connect/certs

server:
  port: 8090

logging:
  level:
    com.toolrent: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html